add-highlighter global/ number-lines -hlcursor -separator " "
add-highlighter global/ regex '\h*$' 0:red,red

hook global InsertCompletionShow .* %{
	map window insert <tab> <c-n>
	map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
	unmap window insert <tab> <c-n>
	unmap window insert <s-tab> <c-p>
}

hook global NormalKey 'y' %{
	nop %sh{
		(printf '%s' "$kak_main_reg_dquote" | xclip -filter | xclip -selection clipboard) < /dev/null > /dev/null 2>&1 &
	}
}

map global normal p '!xclip -selection clipboard -o<ret>'

set-option global indentwidth 0
set-option global tabstop 4

# set cursor to underline
hook global InsertIdle .* %{
	set-face window PrimaryCursor default,default+u
	set-face window PrimaryCursorEol default,default+u
}

# set cursor to default
hook global NormalIdle .* %{
	set-face window PrimaryCursor default,default+r
	set-face window PrimaryCursorEol default,default+r
}

evaluate-commands %sh{
	graft-add https://github.com/alexherbo2/auto-pairs.kak auto-pairs
}

enable-auto-pairs
