add-highlighter global/ number-lines -hlcursor -separator " "
add-highlighter global/ regex '\h*$' 0:red,red

hook global InsertCompletionShow .* %{
	map window insert <tab> <c-n>
	map window insert <s-tab> <c-p>
}

hook global InsertCompletionHide .* %{
	unmap window insert <tab> <c-n>
	unmap window insert <s-tab> <c-p>
}

hook global NormalKey 'y' %{
	nop %sh{
		(printf '%s' "$kak_main_reg_dquote" | xclip -filter | xclip -selection clipboard) < /dev/null > /dev/null 2>&1 &
	}
}

map global normal p '!xclip -selection clipboard -o<ret>'

set-option global indentwidth 0
set-option global tabstop 4

# set cursor to underline
hook global InsertIdle .* %{
	set-face window PrimaryCursor default,default+u
	set-face window PrimaryCursorEol default,default+u
}

# set cursor to default
hook global NormalIdle .* %{
	set-face window PrimaryCursor default,default+r
	set-face window PrimaryCursorEol default,default+r
}

define-command graft -params 1..2 %{
	evaluate-commands %sh{
		plugin_repo="$1"
		plugin_name="${2:-$(basename "$plugin_repo" .git)}"
		autoload_dir="$HOME/.config/kak/autoload"

		if [ ! -d "$autoload_dir" ]; then
			mkdir -p "$autoload_dir" &&
			ln -s /usr/share/kak/rc/* "$autoload_dir" &&
			echo "Initialized autoload directory." >&2
		fi

		if [ ! -d "$autoload_dir/$plugin_name" ]; then
			git clone "$plugin_repo" "$autoload_dir/$plugin_name" &&
			echo "Cloned $plugin_name to autoload." >&2
		fi
	}
}

graft https://github.com/alexherbo2/auto-pairs.kak auto-pairs
graft https://github.com/raiguard/kak-move-lines move-lines

enable-auto-pairs

map global normal <c-s-j> ': move-lines-down %val{count}<ret>'
map global normal <c-s-k> ': move-lines-up %val{count}<ret>'
