#!/bin/sh

rm /tmp/bspc.spawn

c() { bspc config "$@" ;}
m() { bspc monitor "$@" ;}
s() { "$@" & echo "$!" >> /tmp/bspc.spawn ;}
x() { xrdb -q | grep -m1 "$@" | cut -f2 ;}

m -d 1 2 3 4 5 6 7 8 9 0

c border_width				1
c top_padding				0
c window_gap				0
c split_ratio				0.5
c focus_follows_pointer		true
c pointer_follows_focus		true

c focused_border_color		$(x markcolour)
c normal_border_color		$(x background)
c presel_feedback_color		$(x markcolour)

s polybar
s sxhkd
s syncthing -no-browser
s picom

s auto-width
s ybps update
